name: Validate Configuration Scripts

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    name: Shellcheck
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@2.0.0
      with:
        scandir: '.'
        format: gcc
        severity: warning
        ignore_paths: |
          .github
          imgs
  
  syntax-check:
    runs-on: ubuntu-latest
    name: Syntax Check
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check bash syntax
      run: |
        bash -n configure_my_wsl.sh
        bash -n config-aws-kube.sh
        bash -n validate_setup.sh
        bash -n backup_config.sh
    
    - name: Check file permissions
      run: |
        ls -la *.sh
        
    - name: Validate package lists
      run: |
        # Check if package lists are not empty
        if [ ! -s package_list.txt ]; then
          echo "Error: package_list.txt is empty"
          exit 1
        fi
        
        if [ ! -s my_brews.txt ]; then
          echo "Error: my_brews.txt is empty"
          exit 1
        fi
        
        echo "Package lists validation passed"
    
    - name: Check JSON syntax
      run: |
        # Validate settings.json
        if command -v jq &> /dev/null; then
          jq . settings.json > /dev/null
          echo "settings.json is valid JSON"
        else
          echo "jq not available, skipping JSON validation"
        fi
